"""Digest composition service for TLDRist."""

import html
from datetime import datetime, timezone

from tldrist.clients.gemini import ArticleSummary, GeminiClient
from tldrist.services.summarizer import ProcessedArticle
from tldrist.utils.logging import get_logger

logger = get_logger(__name__)


class DigestService:
    """Service for composing the weekly digest email."""

    def __init__(self, gemini_client: GeminiClient) -> None:
        self._gemini = gemini_client

    async def compose_digest(
        self,
        articles: list[ProcessedArticle],
    ) -> tuple[str, str]:
        """Compose the weekly digest email.

        Args:
            articles: List of processed articles to include.

        Returns:
            Tuple of (subject, html_content).
        """
        logger.info("Composing digest", article_count=len(articles))

        if not articles:
            return self._empty_digest()

        summaries = [
            ArticleSummary(url=a.url, title=a.title, summary=a.summary)
            for a in articles
        ]

        intro = await self._gemini.generate_digest_intro(summaries)
        subject = self._generate_subject()
        html = self._render_html(intro, articles)

        logger.info("Digest composed", subject=subject)
        return subject, html

    def _empty_digest(self) -> tuple[str, str]:
        """Generate an empty digest when there are no articles."""
        subject = self._generate_subject()
        html = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
<h1 style="color: #333;">Your Weekly Reading Digest</h1>
<p>No articles were found in your Read list this week.</p>
<p>Add some articles to your Todoist "Read" project to receive summaries next week!</p>
</body>
</html>"""
        return subject, html

    def _generate_subject(self) -> str:
        """Generate the email subject line."""
        date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
        return f"Your Weekly Reading Digest - {date_str}"

    def _render_html(self, intro: str, articles: list[ProcessedArticle]) -> str:
        """Render the digest as HTML."""
        # Escape intro text from LLM to prevent XSS
        safe_intro = html.escape(intro)
        articles_html = "\n".join(
            self._render_article(a) for a in articles
        )

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
    color: #333;
    line-height: 1.6;
}}
h1 {{
    color: #1a1a1a;
    border-bottom: 2px solid #e0e0e0;
    padding-bottom: 10px;
}}
h2 {{
    color: #2c2c2c;
    margin-top: 30px;
}}
.intro {{
    background: #f8f9fa;
    padding: 15px;
    border-radius: 8px;
    margin-bottom: 30px;
}}
.article {{
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 1px solid #e0e0e0;
}}
.article:last-child {{
    border-bottom: none;
}}
.article-title {{
    color: #1a73e8;
    text-decoration: none;
    font-size: 1.2em;
    font-weight: 600;
}}
.article-title:hover {{
    text-decoration: underline;
}}
.summary {{
    margin-top: 10px;
}}
.footer {{
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #e0e0e0;
    font-size: 0.9em;
    color: #666;
}}
</style>
</head>
<body>
<h1>Your Weekly Reading Digest</h1>

<div class="intro">
{safe_intro}
</div>

<h2>This Week's Articles</h2>

{articles_html}

<div class="footer">
<p>This digest was generated by TLDRist using AI summarization.</p>
<p>Articles remain in your Todoist Read list with summaries added to their descriptions.</p>
</div>
</body>
</html>"""

    def _render_article(self, article: ProcessedArticle) -> str:
        """Render a single article as HTML."""
        # Escape all user/external content to prevent XSS
        safe_title = html.escape(article.title)
        safe_url = html.escape(article.url)
        safe_summary = html.escape(article.summary)
        summary_paragraphs = safe_summary.replace("\n\n", "</p><p>")
        return f"""<div class="article">
<a href="{safe_url}" class="article-title">{safe_title}</a>
<div class="summary">
<p>{summary_paragraphs}</p>
</div>
</div>"""
